
services:
  postgres:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     # - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=mysql
  #     - MYSQL_USER=mysql
  #     - MYSQL_PASSWORD=mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data/mysql:/var/lib/mysql

